SuperMarket.Web/Areas/UserPanel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SuperMarket.Core.Convertors;
using SuperMarket.Core.DTOs;
using SuperMarket.Core.Services.Interfaces;

namespace SuperMarket.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    [Authorize]
    public class HomeController : Controller
    {
        private IUserService _userService;
        public HomeController(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult Index()
        {
            return View(_userService.GetUserInformation(User.Identity.Name));
        }

        [Route("UserPanel/EditProfile")]
        public IActionResult EditProfile()
        {
            return View(_userService.GetDataForEditProfileUser(User.Identity.Name));
        }

        [Route("UserPanel/EditProfile")]
        [HttpPost]
        public IActionResult EditProfile(EditProfileViewModel profile)
        {
            if (!ModelState.IsValid)
                return View(profile);
            if (_userService.IsExistEmail(FixedText.FixEmail(profile.Email)))
            {
                ModelState.AddModelError("Email", "ایمیل وارد شده قبلا ثبت نام کرده است.");
                return View(profile);
            }

            _userService.EditProfile(User.Identity.Name, profile);

            ViewBag.IsSuccess = true;

            return View(_userService.GetDataForEditProfileUser(User.Identity.Name));
        }

        [Route("UserPanel/ChangePassword")]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [Route("UserPanel/ChangePassword")]
        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordViewModel changePassword)
        {
            string currentMobile = User.Identity.Name;
            if (!ModelState.IsValid)
                return View(changePassword);

            if(!_userService.CompareOldPassword(changePassword.OldPassword,currentMobile))
            {
                ModelState.AddModelError("OldPassword", "کلمه عبور فعلی صحیح نمی باشد");
                return View(changePassword);
            }

            _userService.ChangeUserPassword(currentMobile, changePassword.Password);
            ViewBag.IsSuccess = true;

            return View();
        }
    }
}

SuperMarket.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using SuperMarket.Core.Convertors;
using SuperMarket.Core.Services;
using SuperMarket.Core.Services.Interfaces;
using SuperMarket.DataLayer.Entites.User;

namespace SuperMarket.Web.Controllers
{

    public class HomeController : Controller
    {
        private IUserService _userService;
        private IProductService _productService;
        private IOrderService _orderService; 
        public HomeController(IUserService userService, IProductService productService,IOrderService orderService)
        {
            _userService = userService;
            _productService = productService;
            _orderService = orderService;
        }
        public IActionResult Index()
        {
            ViewBag.BestsellerProduct = _productService.GetBestSellerProduct();
            ViewBag.GroupMobile = _productService.GetGroupMobile();
            if(User.Identity.IsAuthenticated)
            {
                ViewBag.OrderUserInIndex = _orderService.GetUserOrders(User.Identity.Name);
            }
            return View(_productService.GetProduct().Item1);
        }



        [Route("OnlinePayment/{id}")]
        public IActionResult OnlinePeyment(int id)
        {
            if (HttpContext.Request.Query["Status"] != "" &&
              HttpContext.Request.Query["Status"].ToString().ToLower() == "ok"
              && HttpContext.Request.Query["Authority"] != "")
            {
                string authority = HttpContext.Request.Query["Authority"];

                var wallet = _userService.GetWalletByWalletId(id);

                var payment = new ZarinpalSandbox.Payment(wallet.Amount);
                var res = payment.Verification(authority).Result;
                if (res.Status == 100)
                {
                    ViewBag.code = res.RefId;
                    ViewBag.IsSuccess = true;
                    wallet.IsPay = true;
                    _userService.UpdateWallet(wallet);
                }

            }

            return View();
        }

        public IActionResult GetSubGroups(int id)
        {
            List<SelectListItem> list = new List<SelectListItem>()
            {
                new SelectListItem(){Text="انتخاب کنید",Value="0"}
            };
            list.AddRange(_productService.GetSubGroupForManageProduct(id));
            return Json(new SelectList(list, "Value", "Text"));
        }

        [HttpPost]
        [Route("file-upload")]
        public IActionResult UploadImage(IFormFile upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            if (upload.Length <= 0) return null;

            var fileName = Guid.NewGuid() + Path.GetExtension(upload.FileName).ToLower();



            var path = Path.Combine(
                Directory.GetCurrentDirectory(), "wwwroot/MyImages",
                fileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                upload.CopyTo(stream);

            }



            var url = $"{"/MyImages/"}{fileName}";


            return Json(new { uploaded = true, url });
        }

        public IActionResult Error404()
        {
            return View();
        }

        [Route("AboutUs")]
        public IActionResult AboutUs()
        {
            return View();
        }

        [Route("ContactUs")]
        public IActionResult ContactUs()
        {
            return View();
        }

        [HttpPost]
        [Route("ContactUs")]
        public IActionResult ContactUs(ContactUs contact)
        {
            if (!ModelState.IsValid)
            {
                return View(contact);
            }

            DataLayer.Entites.User.ContactUs contactUs = new ContactUs()
            {
                UserName = contact.UserName,
                Mobile = contact.Mobile,
                Email = FixedText.FixEmail(contact.Email),
                ContactTitle = contact.ContactTitle,
                ContactDescription = contact.ContactDescription,
                IsDelete = false,
                IsAdminRead = false
            };
            _userService.AddContact(contact);

            ViewBag.IsSuccess = true;
            return View(contact);
        }
    }
}

SuperMarket.Web/ViewComponents/LatesProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SuperMarket.Core.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperMarket.Web.ViewComponents
{
    public class LatesProductViewComponent:ViewComponent
    {
        private IProductService _productService;
        public LatesProductViewComponent(IProductService productService)
        {
            _productService = productService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("LatesProduct", _productService.GetProduct().Item1));
        }
    }
}

SuperMarket.Web/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "درباره ما";
}

<div id="container">
    <div class="container">
        <!-- Breadcrumb Start-->
        <ul class="breadcrumb">
            <li><a href="/"><i class="fa fa-home"></i></a></li>
            <li><a href="/AboutUs">درباره ما</a></li>
        </ul>
        <div class="row">    
            <div class="col-sm-3">
                <i class="fa fa-user"></i>
                <strong>برنامه نویس</strong><br />
                حامد محمودی برنامه نویس BackEnd
                <br /><br />
                <i class="fa fa-phone"></i>
                <strong>شماره تماس</strong><br>
                09368686685<br>
                <br>
                <i class="fa fa-envelope"></i>
                <strong>ایمیل</strong><br>
                hamedmahmoodi.42@gmail.com
            </div>
        </div>
    </div>
</div>

SuperMarket.Web/Views/Home/ContactUs.cshtml
@model SuperMarket.DataLayer.Entites.User.ContactUs

@{
    ViewData["Title"] = "تماس با ما";
}

<div id="container">
    <div class="container">
        <!-- Breadcrumb Start-->
                <nav aria-label="breadcrumb">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/"><i class="fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active" aria-current="page">تماس با پشتیبانی</li>
                    </ul>
                </nav>
                <!-- Breadcrumb End-->
                <div class="row">
                    <!--Middle Part Start-->
                    <div id="content" class="col-sm-9">
                        <h3 class="title">تماس با پشتیبانی</h3>
                        @if (ViewBag.IsSuccess != null)
                        {
                            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                            <script>
                        Swal.fire({
                            position: 'top-end',
                            icon: 'success',
                            title: 'پیام شما با موفقیت ثبت شد.',
                            showConfirmButton: false,
                            timer: 3000,
                        })
                        var delay = 3000;
                        setTimeout(function () { window.location = "/"; }, delay);
                            </script>
                        }
                        <section class="user-account-content">
                            <form asp-action="ContactUs" method="post" class="form-horizontal">
                                <fieldset>
                                    <div class="form-group">
                                        <div class="col-sm-6">
                                            <label class="control-label"><i class="far fa-user"></i> نام ونام خانوادگی </label>
                                            <input asp-for="UserName" type="text" value="" class="form-control">
                                        </div>
                                        <div class="col-sm-6">
                                            <label class="control-label"><i class="far fa-phone-square"></i> شماره تماس </label>
                                            <input asp-for="Mobile" type="tel" value="" class="form-control">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class=" col-sm-12">
                                            <label class="control-label"><i class="far fa-envelope"></i> ایمیل </label>
                                            <input asp-for="Email" type="email" value="" class="form-control">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class=" col-sm-12">
                                            <label class="control-label"><i class="far fa-clipboard-list"></i> عنوان </label>
                                            <input asp-for="ContactTitle" type="text" value="" class="form-control">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-8 col-sm-6">
                                            <label class="control-label"><i class="far fa-clipboard-list"></i> توضیحات </label>
                                            <textarea asp-for="ContactDescription" rows="6" class="form-control" placeholder="درج پیام..."></textarea>
                                        </div>
                                    </div>
                                </fieldset>
                                <div asp-validation-summary="All" class="text-danger">
                                </div>
                                <div class="buttons">
                                    <div class="pull-right">
                                        <input type="submit" class="btn btn-primary" value="ارسال">
                                    </div>
                                </div>
                            </form>
                        </section>
                    </div>
                    <!--Middle Part End -->
                </div>
            </div>
        </div>

SuperMarket.Web/Views/Home/Error404.cshtml
<div id="container">
    <div class="container">
        <div class="row">
            <!--Middle Part Start-->
            <div id="content" class="col-sm-12">
                <h1 class="title-404 text-center">404</h1>
                <p class="text-center lead">
                    متأسفیم!<br>
                    صفحه ی مورد نظرتان را پیدا نکردیم!
                </p>
                <div class="buttons text-center"> <a class="btn btn-primary btn-lg" href="/">بازگشت به صفحه اصلی</a> </div>
            </div>
            <!--Middle Part End -->
        </div>
    </div>
</div>

SuperMarket.Web/Views/Home/Index.cshtml
@using SuperMarket.DataLayer.Entites.Product
@using SuperMarket.DataLayer.Entites.Order
@using SuperMarket.Core.DTOs.Product

@{
    ViewData["Title"] = "خانه";
}

@section SearchBox
{
    <header class="header-row">
        <div class="container">
            <div class="table-container">
                <!-- Logo Start -->
                <div class="col-table-cell col-lg-6 col-md-6 col-sm-12 col-xs-12 inner">
                    <div id="logo"><a href="/"><img class="img-responsive" src="/images/logo.png" title="DigiStar" alt="DigiStar" /></a></div>
                </div>
                <!-- Logo End -->
                <!-- جستجو Start-->
                <div class="col-table-cell col-md-5 col-md-push-0 col-sm-6 col-sm-push-6 col-xs-12">
                    <form action="/Product" method="get">
                        <div id="search" class="input-group">
                            <input type="text" name="filter" id="autFilter" placeholder="جستجو در دیجی استار..." class="form-control input-lg" />
                            <button class="button-search"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="col-table-cell col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        @{
                            List<Order> ShowOrderUser = ViewBag.OrderUserInIndex as List<Order>;
                        }
                        @foreach (var item in ShowOrderUser)
                        {
                            <partial name="_CartItem" model="@item" />
                        }
                    </div>
                }
                else
                {
                    <div class="col-table-cell col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div id="cart">
                            <button type="button" data-toggle="dropdown" data-loading-text="Loading..." class="heading dropdown-toggle">
                                <span class="cart-icon pull-left flip"></span>
                                <span id="cart-total">سبد خرید</span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <p class="alert alert-danger">جهت مشاهده سبد خرید وارد سایت شوید</p>
                                    <p class="checkout"><a href="/Login" class="btn btn-primary"> ورود به سایت</a></p>
                                </li>
                            </ul>
                        </div>
                    </div>
                }
                <!-- جستجو End-->
            </div>
        </div>
    </header>
}
<!-- Feature Box Start-->
<div class="container">
    <div class="custom-feature-box row">
        <div class="col-md-4 col-sm-8 col-xs-12">
            <div class="feature-box fbox_1">
                <div class="title">ارسال رایگان</div>
                <p>برای خرید های بیش از 100 هزار تومان</p>
            </div>
        </div>
        <div class="col-md-4 col-sm-8 col-xs-12">
            <div class="feature-box fbox_3">
                <div class="title">کارت هدیه</div>
                <p>بهترین هدیه برای عزیزان شما</p>
            </div>
        </div>
        <div class="col-md-4 col-sm-8 col-xs-12">
            <div class="feature-box fbox_4">
                <div class="title">امتیازات خرید</div>
                <p>از هر خرید امتیاز کسب کرده و از آن بهره بگیرید</p>
            </div>
        </div>
    </div>
</div>
<!-- Feature Box End-->
<div class="container">
    <div class="row">
        <!-- Left Part Start-->
        <aside id="column-left" class="col-sm-3 hidden-xs">

            <div class="banner owl-carousel">
                <div class="item"> <a href="#"><img src="/images/banner/small-banner1-265x350.jpg" alt="small banner" class="img-responsive" /></a> </div>
                <div class="item"> <a href="#"><img src="/images/banner/small-banner-265x350.jpg" alt="small banner1" class="img-responsive" /></a> </div>
            </div>
            <h3 class="subtitle">موبایل</h3>
            <div class="side-item">
                @{
                    List<Product> MobileProduct = ViewBag.GroupMobile as List<Product>;
                }
                @foreach (var item in MobileProduct)
                {
                    <partial name="_viewMobileGroup" model="@item" />
                }
            </div>
        </aside>
        <!-- Left Part End-->
        <div id="content" class="col-sm-9">
            <!-- Slideshow Start-->
            <div class="slideshow single-slider owl-carousel">
                <div class="item"> <a href="/"><img class="img-responsive" src="/images/slider/banner-1.jpg" alt="banner 1" /></a> </div>
                <div class="item"> <a href="/"><img class="img-responsive" src="/images/slider/banner-2.jpg" alt="banner 2" /></a> </div>
                <div class="item"> <a href="/"><img class="img-responsive" src="/images/slider/banner-3.jpg" alt="banner 3" /></a> </div>
            </div>
            <!-- Slideshow End-->
            <h3 class="subtitle">جدیدترین  -<a class="viewall" href="/Product">نمایش همه</a></h3>
            <div class="owl-carousel product_carousel">
                <cache expires-after="@TimeSpan.FromMinutes(1)">
                    @await Component.InvokeAsync("LatesProduct")
                </cache>
            </div>
            <!-- Featured محصولات End-->
            <!-- Banner Start-->
            <div class="marketshop-banner">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"><a href="#"><img src="images/banner/sample-banner-1-400x200.jpg" alt="بنر نمونه 3" title="بنر نمونه 3" /></a></div>
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"><a href="#"><img src="images/banner/sample-banner-4-400x200.jpg" alt="بنر نمونه" title="بنر نمونه" /></a></div>
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"><a href="#"><img src="images/banner/sample-banner-3-400x200.jpg" alt="بنر نمونه 2" title="بنر نمونه 2" /></a></div>
                </div>
            </div>
            <!-- Banner End-->
            <h3 class="subtitle">پرفروش - <a class="viewall" href="/Product/@ViewBag.orderByType">نمایش همه</a></h3>
            <div class="owl-carousel product_carousel">
                @{
                    List<ShowProductListItemViewModel> bestSeller = ViewBag.BestsellerProduct as List<ShowProductListItemViewModel>;
                }
                @if (bestSeller != null)
                {
                    @foreach (var item in bestSeller)
                    {
                        <partial name="_BoxProduct" model="@item" />
                    }
                }
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $("#autFilter").autocomplete({
                source: 'api/productapi/search'
            });
        });
    </script>

}

SuperMarket.Web/Views/Home/OnlinePeyment.cshtml
@{
    ViewData["Title"] = "نتیجه پرداخت";
}

<div id="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/"><i class="fa fa-home"></i></a></li>
            <li class="breadcrumb-item active" aria-current="page">نتیجه پرداخت </li>
        </ul>
    </nav>
</div>

<div class="container">
    @if (ViewBag.IsSuccess == true)
    {
        <div class="alert alert-success">
            <h2>پرداخت با موفقیت انجام شد.</h2>
            <p>کد پیگیری : @ViewBag.Code</p>
        </div>
    }
    else
    {
        <div class="alert alert-danger">
            <h2>پرداخت با شکست مواجه شد!</h2>
        </div>
    }
</div>